### ISSUE TITLE
ETW2JSON fails on GPUView traces

### ISSUE THREAD

**Issue by jrmuizel** [microsoft/ETW2JSON#11]
Running ETW2JSON on https://drive.google.com/file/d/1Qy6sa5dmeAefaVD7pailxde-uCRUL5V3/view?usp=sharing
gives:
```
Unhandled exception. System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.DefaultBinder.SelectMethod(BindingFlags bindingAttr, MethodBase[] match, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at ETWDeserializer.Extensions.GetMethodInfo(Type type, String name, Type[] parameterType) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Extensions.cs:line 369
   at ETWDeserializer.Extensions.ReadMethodInfo(TDH_IN_TYPE tdhType, Type type, Type[] parameterType) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Extensions.cs:line 252
   at ETWDeserializer.EventTraceOperandExpressionBuilderImpl.ExpressionGenerator.CodeGenerate(IEnumerable`1 operands) in C:\Users\mozilla\src\ETW2JSON\Deserializer\EventTraceOperandExpressionBuilder.cs:line 104
   at ETWDeserializer.EventTraceOperandExpressionBuilderImpl.Build(IEventTraceOperand operand, ParameterExpression eventRecordReader, ParameterExpression eventRecordWriter, ParameterExpression eventMetadataTable, ParameterExpression runtimeMetadata) in C:\Users\mozilla\src\ETW2JSON\Deserializer\EventTraceOperandExpressionBuilder.cs:line 43
   at ETWDeserializer.EventTraceOperandExpressionBuilder.Build(IEventTraceOperand operand, ParameterExpression eventRecordReader, ParameterExpression eventRecordWriter, ParameterExpression eventMetadataTable, ParameterExpression runtimeMetadata) in C:\Users\mozilla\src\ETW2JSON\Deserializer\EventTraceOperandExpressionBuilder.cs:line 18
   at ETWDeserializer.Deserializer`1.SlowLookup(EVENT_RECORD* eventRecord, EventRecordReader eventRecordReader, RuntimeEventMetadata runtimeMetadata, TraceEventKey& key) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Deserializer.cs:line 251
   at ETWDeserializer.Deserializer`1.Deserialize(EVENT_RECORD* eventRecord) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Deserializer.cs:line 71
   at ETW2JSON.Etw.ProcessTrace(UInt64[] HandleArray, UInt32 HandleCount, IntPtr StartTime, IntPtr EndTime)
   at ETW2JSON.Program.ConvertToJson(Utf8JsonWriter jsonWriter, IEnumerable`1 inputFiles, Action`1 reportError) in C:\Users\mozilla\src\ETW2JSON\Program.cs:line 74
   at ETW2JSON.Program.Main(String[] args) in C:\Users\mozilla\src\ETW2JSON\Program.cs:line 117
```

**Comment by Tridhatri** [comment]
> Running ETW2JSON on https://drive.google.com/file/d/1Qy6sa5dmeAefaVD7pailxde-uCRUL5V3/view?usp=sharing gives:
> 
> ```
> Unhandled exception. System.Reflection.AmbiguousMatchException: Ambiguous match found.
>    at System.DefaultBinder.SelectMethod(BindingFlags bindingAttr, MethodBase[] match, Type[] types, ParameterModifier[] modifiers)
>    at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
>    at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
>    at ETWDeserializer.Extensions.GetMethodInfo(Type type, String name, Type[] parameterType) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Extensions.cs:line 369
>    at ETWDeserializer.Extensions.ReadMethodInfo(TDH_IN_TYPE tdhType, Type type, Type[] parameterType) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Extensions.cs:line 252
>    at ETWDeserializer.EventTraceOperandExpressionBuilderImpl.ExpressionGenerator.CodeGenerate(IEnumerable`1 operands) in C:\Users\mozilla\src\ETW2JSON\Deserializer\EventTraceOperandExpressionBuilder.cs:line 104
>    at ETWDeserializer.EventTraceOperandExpressionBuilderImpl.Build(IEventTraceOperand operand, ParameterExpression eventRecordReader, ParameterExpression eventRecordWriter, ParameterExpression eventMetadataTable, ParameterExpression runtimeMetadata) in C:\Users\mozilla\src\ETW2JSON\Deserializer\EventTraceOperandExpressionBuilder.cs:line 43
>    at ETWDeserializer.EventTraceOperandExpressionBuilder.Build(IEventTraceOperand operand, ParameterExpression eventRecordReader, ParameterExpression eventRecordWriter, ParameterExpression eventMetadataTable, ParameterExpression runtimeMetadata) in C:\Users\mozilla\src\ETW2JSON\Deserializer\EventTraceOperandExpressionBuilder.cs:line 18
>    at ETWDeserializer.Deserializer`1.SlowLookup(EVENT_RECORD* eventRecord, EventRecordReader eventRecordReader, RuntimeEventMetadata runtimeMetadata, TraceEventKey& key) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Deserializer.cs:line 251
>    at ETWDeserializer.Deserializer`1.Deserialize(EVENT_RECORD* eventRecord) in C:\Users\mozilla\src\ETW2JSON\Deserializer\Deserializer.cs:line 71
>    at ETW2JSON.Etw.ProcessTrace(UInt64[] HandleArray, UInt32 HandleCount, IntPtr StartTime, IntPtr EndTime)
>    at ETW2JSON.Program.ConvertToJson(Utf8JsonWriter jsonWriter, IEnumerable`1 inputFiles, Action`1 reportError) in C:\Users\mozilla\src\ETW2JSON\Program.cs:line 74
>    at ETW2JSON.Program.Main(String[] args) in C:\Users\mozilla\src\ETW2JSON\Program.cs:line 117
> ```

Is there a workaround for this?
